//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvogadosOab.AdvogadoOABWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdvogadoOABWS.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since message ConsultaAdvogadoPorCpfRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaAdvogadoPorCpf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfResponse ConsultaAdvogadoPorCpf(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaAdvogadoPorCpf", ReplyAction="*")]
        System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfResponse> ConsultaAdvogadoPorCpfAsync(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest request);
        
        // CODEGEN: Generating message contract since message ConsultaAdvogadoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaAdvogado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoResponse ConsultaAdvogado(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaAdvogado", ReplyAction="*")]
        System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoResponse> ConsultaAdvogadoAsync(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest request);
        
        // CODEGEN: Generating message contract since message BuscaImagemAdvogadoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaImagemAdvogado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoResponse BuscaImagemAdvogado(AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaImagemAdvogado", ReplyAction="*")]
        System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoResponse> BuscaImagemAdvogadoAsync(AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaAdvogadoPorCpf", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaAdvogadoPorCpfRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AdvogadosOab.AdvogadoOABWS.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cpf;
        
        public ConsultaAdvogadoPorCpfRequest() {
        }
        
        public ConsultaAdvogadoPorCpfRequest(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, string cpf) {
            this.Authentication = Authentication;
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaAdvogadoPorCpfResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaAdvogadoPorCpfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ConsultaAdvogadoPorCpfResult;
        
        public ConsultaAdvogadoPorCpfResponse() {
        }
        
        public ConsultaAdvogadoPorCpfResponse(string ConsultaAdvogadoPorCpfResult) {
            this.ConsultaAdvogadoPorCpfResult = ConsultaAdvogadoPorCpfResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaAdvogado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaAdvogadoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AdvogadosOab.AdvogadoOABWS.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string inscricao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string uf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nome;
        
        public ConsultaAdvogadoRequest() {
        }
        
        public ConsultaAdvogadoRequest(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, string inscricao, string uf, string nome) {
            this.Authentication = Authentication;
            this.inscricao = inscricao;
            this.uf = uf;
            this.nome = nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaAdvogadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultaAdvogadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ConsultaAdvogadoResult;
        
        public ConsultaAdvogadoResponse() {
        }
        
        public ConsultaAdvogadoResponse(string ConsultaAdvogadoResult) {
            this.ConsultaAdvogadoResult = ConsultaAdvogadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscaImagemAdvogado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscaImagemAdvogadoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AdvogadosOab.AdvogadoOABWS.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int numeroSeguranca;
        
        public BuscaImagemAdvogadoRequest() {
        }
        
        public BuscaImagemAdvogadoRequest(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, int numeroSeguranca) {
            this.Authentication = Authentication;
            this.numeroSeguranca = numeroSeguranca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscaImagemAdvogadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscaImagemAdvogadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] BuscaImagemAdvogadoResult;
        
        public BuscaImagemAdvogadoResponse() {
        }
        
        public BuscaImagemAdvogadoResponse(byte[] BuscaImagemAdvogadoResult) {
            this.BuscaImagemAdvogadoResult = BuscaImagemAdvogadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : AdvogadosOab.AdvogadoOABWS.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AdvogadosOab.AdvogadoOABWS.ServiceSoap>, AdvogadosOab.AdvogadoOABWS.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfResponse AdvogadosOab.AdvogadoOABWS.ServiceSoap.ConsultaAdvogadoPorCpf(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest request) {
            return base.Channel.ConsultaAdvogadoPorCpf(request);
        }
        
        public string ConsultaAdvogadoPorCpf(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, string cpf) {
            AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest inValue = new AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest();
            inValue.Authentication = Authentication;
            inValue.cpf = cpf;
            AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfResponse retVal = ((AdvogadosOab.AdvogadoOABWS.ServiceSoap)(this)).ConsultaAdvogadoPorCpf(inValue);
            return retVal.ConsultaAdvogadoPorCpfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfResponse> AdvogadosOab.AdvogadoOABWS.ServiceSoap.ConsultaAdvogadoPorCpfAsync(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest request) {
            return base.Channel.ConsultaAdvogadoPorCpfAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfResponse> ConsultaAdvogadoPorCpfAsync(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, string cpf) {
            AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest inValue = new AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoPorCpfRequest();
            inValue.Authentication = Authentication;
            inValue.cpf = cpf;
            return ((AdvogadosOab.AdvogadoOABWS.ServiceSoap)(this)).ConsultaAdvogadoPorCpfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoResponse AdvogadosOab.AdvogadoOABWS.ServiceSoap.ConsultaAdvogado(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest request) {
            return base.Channel.ConsultaAdvogado(request);
        }
        
        public string ConsultaAdvogado(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, string inscricao, string uf, string nome) {
            AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest inValue = new AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest();
            inValue.Authentication = Authentication;
            inValue.inscricao = inscricao;
            inValue.uf = uf;
            inValue.nome = nome;
            AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoResponse retVal = ((AdvogadosOab.AdvogadoOABWS.ServiceSoap)(this)).ConsultaAdvogado(inValue);
            return retVal.ConsultaAdvogadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoResponse> AdvogadosOab.AdvogadoOABWS.ServiceSoap.ConsultaAdvogadoAsync(AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest request) {
            return base.Channel.ConsultaAdvogadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoResponse> ConsultaAdvogadoAsync(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, string inscricao, string uf, string nome) {
            AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest inValue = new AdvogadosOab.AdvogadoOABWS.ConsultaAdvogadoRequest();
            inValue.Authentication = Authentication;
            inValue.inscricao = inscricao;
            inValue.uf = uf;
            inValue.nome = nome;
            return ((AdvogadosOab.AdvogadoOABWS.ServiceSoap)(this)).ConsultaAdvogadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoResponse AdvogadosOab.AdvogadoOABWS.ServiceSoap.BuscaImagemAdvogado(AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest request) {
            return base.Channel.BuscaImagemAdvogado(request);
        }
        
        public byte[] BuscaImagemAdvogado(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, int numeroSeguranca) {
            AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest inValue = new AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest();
            inValue.Authentication = Authentication;
            inValue.numeroSeguranca = numeroSeguranca;
            AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoResponse retVal = ((AdvogadosOab.AdvogadoOABWS.ServiceSoap)(this)).BuscaImagemAdvogado(inValue);
            return retVal.BuscaImagemAdvogadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoResponse> AdvogadosOab.AdvogadoOABWS.ServiceSoap.BuscaImagemAdvogadoAsync(AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest request) {
            return base.Channel.BuscaImagemAdvogadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoResponse> BuscaImagemAdvogadoAsync(AdvogadosOab.AdvogadoOABWS.Authentication Authentication, int numeroSeguranca) {
            AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest inValue = new AdvogadosOab.AdvogadoOABWS.BuscaImagemAdvogadoRequest();
            inValue.Authentication = Authentication;
            inValue.numeroSeguranca = numeroSeguranca;
            return ((AdvogadosOab.AdvogadoOABWS.ServiceSoap)(this)).BuscaImagemAdvogadoAsync(inValue);
        }
    }
}
